### ISSUE TITLE
Stickers for 13x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#103]
Assuming it's the same vendor and size as last year, this is the template:
http://www.stickermule.com/templates/sticker-sheets

**Comment by ScislaC** [comment]
Bala and others, how about this look for the die cut one?
![scale_die_cut](https://cloud.githubusercontent.com/assets/1201009/5929358/d76c23a2-a637-11e4-9b8a-f6d2b5e74180.png)

**Comment by hriday** [comment]
Looks good.

**Comment by ScislaC** [comment]
Sorry, experienced the worst timing ever as an Inkscape release was pushed out this week so I've been trying to balance both things.
![rect15926](https://cloud.githubusercontent.com/assets/1201009/5986489/52c5781e-a8ae-11e4-88cd-e330e36e817f.png)
