### ISSUE TITLE
Mugs for 13x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#104]
@hriday Please let us know specs once you've decided closer to the event.

**Comment by ScislaC** [comment]
Any feedback is appreciated, this is based on us going with the mug bala gave me specs for.
![mug2](https://cloud.githubusercontent.com/assets/1201009/5680887/c9a0b040-97c7-11e4-8e37-50679b6882a1.png)

**Comment by hriday** [comment]
Love it.

—

**Comment by lcafiero** [comment]
+1 - that's great!

**Comment by JasonRkr** [comment]
Group,

This may have been mentioned before so excuse me if I'm repeating stuff,
but isn't the horseshoe supposed to be facing up so the luck doesn't run
out? At least that's how I remember it.  😊

Regards,

Jason

**Comment by Orv** [comment]
+1!

**Comment by ScislaC** [comment]
@JasonRkr You know what, while that doesn't sound familiar to me, wikipedia does confirm that this is correct. Thank you for catching it!

**Comment by ScislaC** [comment]
![mug2](https://cloud.githubusercontent.com/assets/1201009/5682200/1ad65d4c-97d3-11e4-91f6-15000a2a1bd5.png)

**Comment by ScislaC** [comment]
It even looks luckier now ;)

**Comment by garethgreenaway** [comment]
Looks great.

**Comment by itdirector** [comment]
...aaand now I see it. :-)  this is a fun design.

...lori
