### ISSUE TITLE
Attendee shirts for 13x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#105]
Create front and back designs for T-shirts. Any special requirements will be known closer to the event.

**Comment by ScislaC** [comment]
I'm digging this as a front, but if others would like, I can see about whipping some alternates up.
![attendee-front1a](https://cloud.githubusercontent.com/assets/1201009/5966585/8a8f85c2-a7ba-11e4-97e9-c87bbfd4cd72.png)

Here are a few ideas on backs...
![attendee-back1](https://cloud.githubusercontent.com/assets/1201009/5966631/0448daa8-a7bb-11e4-83dd-088f48e00d37.png)
![attendee-back2](https://cloud.githubusercontent.com/assets/1201009/5966671/53c80dc4-a7bb-11e4-9af8-8d946d3d39e2.png)
![attendee-back3](https://cloud.githubusercontent.com/assets/1201009/5966675/599dc5cc-a7bb-11e4-9cfc-d5f4c3f080e1.png)

Open for feedback as usual.

**Comment by irabinovitch** [comment]
Really liking the design this year.

**Comment by garethgreenaway** [comment]
@ScislaC Looking good!  What about having the charms around the circle on the front of the shirt?

**Comment by ScislaC** [comment]
With rotation:
![attendee-front2a](https://cloud.githubusercontent.com/assets/1201009/5968218/fb21afae-a7c9-11e4-9304-04e436dd4ef2.png)

-

Without rotation:
![attendee-front2b](https://cloud.githubusercontent.com/assets/1201009/5968222/01db43d2-a7ca-11e4-8d69-08e850ceb958.png)

**Comment by garethgreenaway** [comment]
Did you have a color for the shirt in mind?  Let me know if you want to see the available colors.

**Comment by ScislaC** [comment]
I'd definitely be interested in seeing available colors, because I have a color in mind for next year.

**Comment by garethgreenaway** [comment]
Do you think we can finalize the design by Monday?  We're getting really close and need to send in the order as soon as possible.

**Comment by ScislaC** [comment]
Oh yeah, I can have the PDFs in your inbox by Monday morning. It just didn't seem like there was a consensus (Ilan liked where it was going, you asked for a mod but didn't comment on it). If it's up to me to just choose, that is totally fine by me... but I don't want people to feel left out of it being an open process for decision.

**Comment by garethgreenaway** [comment]
Sorry, I thought I had responded.  I like the charms around the outside.  Leaning more towards without the rotation but I can go either way.  We can pass the design along to the chairs list and see what everyone things.

**Comment by ScislaC** [comment]
Adding this based on Ilan's last comment
![attendee-back2-alt](https://cloud.githubusercontent.com/assets/1201009/5994405/f99a4a60-aa26-11e4-972b-d91cf4cbffc5.png)
