### ISSUE TITLE
Bag art for 13x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#106]
@hriday If we're going with a different bag for 13x, please let me know the specs when you are aware of them.

**Comment by ScislaC** [comment]
![bag2](https://cloud.githubusercontent.com/assets/1201009/5640056/5f2b53e4-95d5-11e4-9178-a1f2416ed2d7.png)

I will be working on simplifying the coins in the pot of gold at the end of the rainbow... but here's where it stands currently.

**Comment by ScislaC** [comment]
There was no decent simplification of the coins and halftoned rainbow which would take a reasonable amount of time... lucky penny it is. Any feedback would be appreciated since it's effectively finalized with no objections.
![bag3](https://cloud.githubusercontent.com/assets/1201009/5680755/5aad5b08-97c6-11e4-9a64-ea14d5713f6f.png)

**Comment by ScislaC** [comment]
Thanks to a lucky catch on the mug (har har)...
![bag3](https://cloud.githubusercontent.com/assets/1201009/5682246/49cdde22-97d3-11e4-8aae-2fb2a9d8566c.png)

**Comment by garethgreenaway** [comment]
NO objections. Looks great.

**Comment by itdirector** [comment]
i was going to point out that the horseshoe is supposed to face up, but i
see that has changed already. :-)  i didn't see the convo about the mugs.

...lori

**Comment by hriday** [comment]
Josh, it looks like we have a quorum. Let's get the art in the right format
and I'll get it ordered.

Everyone ok with the bag art?

Bala.
