### ISSUE TITLE
New twitter photo for SCALE 13x.

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#111]
Twitter photo for socallinuxexpo account needs updating for SCALE 13x along with the 13x dates.

**Comment by ScislaC** [comment]
Here's an updated avatar with newer dates...
![twitter-avatar](https://cloud.githubusercontent.com/assets/1201009/5641932/1e709b22-95f6-11e4-9ddc-218321a80c1f.png)

**Comment by garethgreenaway** [comment]
Thanks! Looks like someone put it in place.
