### ISSUE TITLE
Badges for 13x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#113]
Here are current badge ideas, feedback welcome. I'm willing to change or adapt whatever, but figured feedback would help move them along...

![badge1](https://cloud.githubusercontent.com/assets/1201009/5913350/72741306-a597-11e4-89cb-0d7cbd621d36.png)
![badge2](https://cloud.githubusercontent.com/assets/1201009/5913352/7672c376-a597-11e4-93e5-ed01d1fddd39.png)
![badge3](https://cloud.githubusercontent.com/assets/1201009/5913353/7aa89ca4-a597-11e4-8edf-629146dafa1c.png)
![badge4](https://cloud.githubusercontent.com/assets/1201009/5913355/80eb7802-a597-11e4-8d30-6bbef0d085cf.png)

**Comment by garethgreenaway** [comment]
These look great.  A bit of feedback:
#1 maybe a few less charms?  Maybe we could have different versions with different charms.
#2 looks good
#3 maybe different version of it, with different colors and charms?
#4 Also good, maybe a few versions with different charms.

**Comment by irabinovitch** [comment]
Strong preference on #1.  I'm still not a huge fan of the frontward facing
Troy.


Lei, does this design work for your printing needs?

**Comment by ScislaC** [comment]
Gareth: 1 has all... 13 charms. :) I could definitely do different versions with a smaller number. 3 was kind of "organic" in that it had a ladybug on a 4-leaf clover. I can definitely do that for 4.

Ilan: 1 doesn't have any front facing troy I'm seeing, did you mean 4?

**Comment by irabinovitch** [comment]
Yes, i meant that the reason I like 1 over 4 is the charms + no front
facing troy.

**Comment by itdirector** [comment]
i like #1 because it so clearly repeats the theme that's on the other
gear.  but the others are visually appealing as well.  are we going to do
more than one badge?

...lori

**Comment by irabinovitch** [comment]
No strong preference here. We can do multiple designs too, as long as
the text box areas are aligned.

Looks like there's enough space there.

**Comment by hriday** [comment]
So, shall I  order?

**Comment by ScislaC** [comment]
That's up to you. I was going to do a few variations on the first one today, I will have them posted in a few hours.

**Comment by hriday** [comment]
Ok, I'll order eod?

**Comment by ScislaC** [comment]
I'm not opposed. I'll just need to know what's being used so I can provide the images to the spec they want.

**Comment by ScislaC** [comment]
I wasn't really happy with the couple other designs I came up with, so I modified the first one with colorized charms to see if it's maybe more appealing to Gareth,
![badge1a](https://cloud.githubusercontent.com/assets/1201009/5949374/d467c59c-a701-11e4-9394-22cd6652260e.png)

**Comment by garethgreenaway** [comment]
I definitely like the multiple charms more when they're in color.
