### ISSUE TITLE
Tech & A/V Team shirts

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#114]

**Comment by ScislaC** [comment]
A/V Back:
![av-back](https://cloud.githubusercontent.com/assets/1201009/5929402/606f6aa6-a638-11e4-8f6f-66387f6c1bde.png)
Emblem A/V team wants on the front:
![emblem_logo](https://cloud.githubusercontent.com/assets/1201009/5929442/a80e0bec-a638-11e4-9acf-bbcfca908f8d.png)

**Comment by garethgreenaway** [comment]
Tech team shirts should be the same design as last year, with the SCALE year and password updated.

**Comment by ScislaC** [comment]
Tech team back:
![tech-back](https://cloud.githubusercontent.com/assets/1201009/5929473/f40f8e94-a638-11e4-9d68-b7efe32fc24e.png)

Waiting on new wifi password for front.

**Comment by garethgreenaway** [comment]
Wireless password will be krowten

**Comment by ScislaC** [comment]
![tech-front](https://cloud.githubusercontent.com/assets/1201009/5930275/5a18410a-a642-11e4-98af-a2bb1e191cdc.png)

**Comment by garethgreenaway** [comment]
Looks good.  If you're feeling creative and have some time. :)  Penguin face as a skull & crossbones :)

**Comment by garethgreenaway** [comment]
http://g.itux.info/var/albums/Dragon_Tux_by_ghassan747.jpg?m=1376786170

**Comment by ScislaC** [comment]
Is that something you got permission to modify and use?

**Comment by hriday** [comment]
Does Gareth need permission if it looks like him?

**Comment by ScislaC** [comment]
If that was posted for reference in asking if we could give that look to the existing penguin on the back of the shirt, then it's not a problem (but that also requires me fleshing out the rest of the penguin). If it's actually wanting that, just modified for the T-shirt, it's a copyright issue without permission.

**Comment by ScislaC** [comment]
By "that look" I mean taloned feet and having wings.

**Comment by garethgreenaway** [comment]
To reiterate what I said in IRC, let's see how this looks for the front with the password.
