### ISSUE TITLE
Enable Featured Speakers Module

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#115]
I created the featured speakers content type, please help enable it on the home page.  Setting promote to front page or stick at top of lists didn't seem to do it.

**Comment by rgolan** [comment]
I think we changed how this works last year. Just make a presentation 'Sticky at top of lists' and that speaker will be a featured speaker. If when you do that, there is something different you need let me know.

**Comment by irabinovitch** [comment]
Ah. Yes. Thanks. seems to work.
