### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#116]
The general 2'x3' signage we have giving directions and by doors.

**Comment by ScislaC** [comment]
Here are a couple ideas John came up with to get some feedback (if anyone has any... I have my thoughts but want to hear from others):

![sign1](https://cloud.githubusercontent.com/assets/1201009/6014177/3d51644e-ab14-11e4-810f-beef7d03744f.jpg)
![sign2](https://cloud.githubusercontent.com/assets/1201009/6014178/41c93d30-ab14-11e4-9447-b6d4434bcefd.jpg)

Obviously ignore the Faux sponsor and repeating "registration" (I just told him he needed to account for longer sign names).

**Comment by irabinovitch** [comment]
Nifty.  Should we incorporate the charms theme at all, or is that overdone?

**Comment by JasonRkr** [comment]
Group,

How about a single charm on each sign?  Just repeat as needed.

Jason

**Comment by irabinovitch** [comment]
All for that if its not a lot of work for john and josh.

**Comment by ScislaC** [comment]
Single charm was actually what I was thinking (something subtle). Thanks for the feedback, I will get back with John.

**Comment by garethgreenaway** [comment]
Those look great.  very eye catching.

**Comment by irabinovitch** [comment]
Thanks Josh.
