### ISSUE TITLE
update social media links on scale13x pages

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#117]
Lanyrd - http://lanyrd.com/2015/scale13x/
Facebook - https://www.facebook.com/events/887579767940460/
G+  - https://plus.google.com/u/0/events/ccj5amj650h88d15h2vgn81cvng

We should drop identica as its no longer active.

**Comment by rgolan** [comment]
I've made those changes.

**Comment by irabinovitch** [comment]
Thanks
