### ISSUE TITLE
"I'm Going" & "I'm Speaking" Badges for SCALE 14x

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#118]
Like we had last year, for people to advertise that they're or they're speaking at SCALE 14x.

**Comment by ScislaC** [comment]
Let me know if alternate sizes or designs are desired...
![attendee-webbadge-small](https://cloud.githubusercontent.com/assets/1201009/11521388/89f865d8-9860-11e5-9f1a-6820f81908dc.png) ![speaker-webbadge-small](https://cloud.githubusercontent.com/assets/1201009/11521389/89fa9bd2-9860-11e5-8661-3b620cb0d2e1.png)

**Comment by garethgreenaway** [comment]
Those look great!

**Comment by lcafiero** [comment]
Are these ready for public consumption?

**Comment by irabinovitch** [comment]
Added them here:
https://www.socallinuxexpo.org/scale/14x/promo-items

**Comment by garethgreenaway** [comment]
@ScislaC Other sizes from last year: https://www.socallinuxexpo.org/scale/13x/promo-items

**Comment by irabinovitch** [comment]
I dont think it's worth the time/effort to create more sizes for the attending/speaking badges. Lets stick with 125x125.

**Comment by garethgreenaway** [comment]
@ScislaC How much time/effort is involved in creating badges of the other sizes we had last year?  I'd imagine you have these as vector graphics and can just resize, then export?

**Comment by garethgreenaway** [comment]
On second thought, the smaller ones do get more use.

**Comment by garethgreenaway** [comment]
Turns out 125x125 is too small for Facebook profile pictures.  Probably the reason we had the larger sizes last year.

**Comment by ScislaC** [comment]
According to FB, this would be the closest match to what is displayed (and is their smallest allowable size 180x180)...
![attendee-webbadge-small](https://cloud.githubusercontent.com/assets/1201009/11537241/0686d8c6-98d1-11e5-8b51-4fc716353a58.png) ![badge-small1x](https://cloud.githubusercontent.com/assets/1201009/11537242/06904640-98d1-11e5-9c9b-936fde3d00aa.png)

Here is the Twitter sized one (400x400)...
![attendee-webbadge-large](https://cloud.githubusercontent.com/assets/1201009/11537278/299e3502-98d1-11e5-89be-ed2809f559c5.png) ![badge-large](https://cloud.githubusercontent.com/assets/1201009/11537279/29a861b2-98d1-11e5-96fd-2a4111c41c19.png)

**Comment by garethgreenaway** [comment]
Looks good!
