### ISSUE TITLE
Facebook header image for SCALE 14x

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#122]
Lets create a SCALE 14x header image for Facebook.

**Comment by irabinovitch** [comment]
2560 x 1440 px

**Comment by ScislaC** [comment]
I've attached a couple things here... 1st is a purely SCALE branded cover. I am concerned though with how much redundancy we want with SCALE being all over the place (lack of prominent SCALE feels wrong though too).
![cover2](https://cloud.githubusercontent.com/assets/1201009/11546229/c792b682-9900-11e5-931d-a1db412b27ed.png)

2nd is a cover with the written out event name and 3rd is a profile pic to pair with it so we get the SCALE 14x in there too.
![cover3](https://cloud.githubusercontent.com/assets/1201009/11546230/cb2972d6-9900-11e5-96dd-f220fb4fe5e9.png)
![profile-pic](https://cloud.githubusercontent.com/assets/1201009/11546235/d236ed9c-9900-11e5-9921-614a4038a305.png)

These can be tweaked after I get some feedback if you would like.

**Comment by garethgreenaway** [comment]
The first one looks great!  I think we should go with that one.

**Comment by irabinovitch** [comment]
Of the 2 I prefer the first one, but ideally troy / scale and the pasadena logo would be a bit more prominent. Im not sure anyone will connect the building itself with pasadena.

**Comment by ScislaC** [comment]
Is this more appealing?
![cover4](https://cloud.githubusercontent.com/assets/1201009/11549476/3b53cdd0-991b-11e5-9a99-8c0df86c6c1d.png)

**Comment by ScislaC** [comment]
Here's an approximation of what it would look like on the page with the last cover and the proposed year specific profile pic... I think people will get enough SCALE & Troy with the combo... :)
 (for the record, I don't have access to FB to change graphics, which is why I mocked this up)
![combined](https://cloud.githubusercontent.com/assets/1201009/11551802/9646d3f2-9931-11e5-9914-5892e2829b92.png)

**Comment by lcafiero** [comment]
I think it's great. I already added it to the Facebook page. Thanks, Josh!

**Comment by ScislaC** [comment]
I'm not seeing it on either https://www.facebook.com/socallinuxexpo/ or the event page... (not questioning, just confused)

**Comment by garethgreenaway** [comment]
I can confirm it's there now and it looks great!

**Comment by ScislaC** [comment]
Since it appears we're sticking with the non year specific profile pic, can someone with access change it to this one since it will probably look a bit sharper?
![profile-pic-generic](https://cloud.githubusercontent.com/assets/1201009/11567430/e5c0f740-999b-11e5-9516-d500466b8ad4.png)

**Comment by garethgreenaway** [comment]
Done.
