### ISSUE TITLE
custom artwork for youtube channel

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#123]
SCALE uses Youtube for our live streaming and on demand recordings of SCALE shows and content.
At the moment our [channel](http://youtube.com/socallinuxexpo) is using the default layout and artwork. 

It'd be great to SCALE brand it. Would anyone be interested in creating custom artwork for the youtube channel?

Instructions for how to do so are available here:
https://support.google.com/youtube/answer/2972003?hl=en

**Comment by forgetpasword** [comment]
I can do it. for this i need scale logo with .cdr extension.

**Comment by irabinovitch** [comment]
@forgetpasword Hi, we dont have much in CDR but you can find a lot of our branding elements here on github https://github.com/socallinuxexpo/SCALE-Design/tree/master/branding in AI, SVG or PDF.

**Comment by ScislaC** [comment]
@forgetpasword Two logos and a copy of Troy are directly available here: https://www.dropbox.com/sh/2bev5bl8va69rqn/AABsGesjGPDMnkYbTY2H340-a?dl=0

We do tend to prefer that open file formats are used, and most of our graphics work tends to be produced with Inkscape, Scribus, Krita, GIMP, Blender, etc. However, if Corel Draw is just more productive for you we understand that and would just ask to receive a PDF of your work along side the items produced to spec.

**Comment by irabinovitch** [comment]
@forgetpasword Thanks for volunteering to look at this. Were you able to access the files @ScislaC  shared?

**Comment by irabinovitch** [comment]
@forgetpasword Just checking back in. Thanks!

**Comment by irabinovitch** [comment]
@forgetpasword hey, happy new year! just wanted to check back in and see if you still might be interested in giving this a shot.
