### ISSUE TITLE
update lanyard button on SCALE website for 2016

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#124]
The new lanyrd link is http://lanyrd.com/2016/scale14x/. Lets update it on SCALE 14x pages. Thanks.

**Comment by rgolan** [comment]
I updated the Lanyrd link. Do any of the other social media links need to be updated?

**Comment by irabinovitch** [comment]
We'll need to update the facebook event, ill work on creating that shortly.

**Comment by irabinovitch** [comment]
@rgolan  Here is the G+ event Link:
https://plus.google.com/b/117542657599667543533/events/cs11bfcssloncm48dj1334gli6c?pageId=117542657599667543533

**Comment by rgolan** [comment]
I updated the G+ link.

**Comment by irabinovitch** [comment]
Thanks.

**Comment by irabinovitch** [comment]
@rgolan  It looks like the buttons reverted to 13x at some point. Can you take a look?

Facebook  - https://www.facebook.com/events/1598162047129055/
G+ - https://plus.google.com/b/117542657599667543533/events/cs11bfcssloncm48dj1334gli6c?pageId=117542657599667543533
Lanyard - http://lanyrd.com/2016/scale14x/

**Comment by rgolan** [comment]
I changed these again but I don't see how they could have been reverted with reverting the whole database.
