### ISSUE TITLE
SCALE 14x Print ads

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#125]
Tracking ticket for print ads we'll want to design. Specs to follow.

**Comment by irabinovitch** [comment]
Specs for Linux Journal. 

http://www.linuxjournal.com/advertising/edcal2015

We can start running ads from Aug 4th if we have the artwork ready by then.

**Comment by irabinovitch** [comment]
Just pinging a reminder that we can get this in on Aug 4th. Next deadline after that is first week of September.

**Comment by ScislaC** [comment]
If you would like to get one in, I can have something ready by 4pm.

**Comment by irabinovitch** [comment]
That would be great. Thanks Josh.

**Comment by irabinovitch** [comment]
This was submitted.
