### ISSUE TITLE
Full Circle Ad

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#127]
We have a full page ad in Full Circle (an Ubuntu community magazine)  through SCALE in January.
Their ad deadline is the 23rd of each month.

The requirements they provided are:  landscape, A4, no more than 100DPI.  
We can use the promo code FULL in the artwork.

**Comment by ScislaC** [comment]
Submitted earlier today.

**Comment by irabinovitch** [comment]
Thanks!
