### ISSUE TITLE
Linux Pro Magazine  Print Ads

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#128]
Hi @ScislaC ,

We've arranged for full page ads in the following issues of Linux New Media publications. 

Linux Pro Issue 181 December 2015
On sale: Dec 4
Art due date: Oct 7

Linux Pro Issue 182 January 2016
On sale: Jan 1
Art due date: Nov 4

ADMIN magazine Issue Dec/Jan
On sale: Nov 13
Art due date: Sept 23

Ubuntu User Winter 2015
On sale: Dec 18
Art due date: Oct 28

**Comment by irabinovitch** [comment]
Ad Specs are available at https://www.dropbox.com/s/il3v8b6qy41wqld/LinuxPro_2015_ad_specs.pdf?dl=0

**Comment by ScislaC** [comment]
ADMIN submitted earlier today, used the promo code ADMIN.

**Comment by irabinovitch** [comment]
Next due date is Wednesday, October 28 for Ubuntu User.

**Comment by irabinovitch** [comment]
@ScislaC we all set for tomorrow?

**Comment by irabinovitch** [comment]
nov artwork submitted.

Last deadline will be in early December.

**Comment by ScislaC** [comment]
Whaich magazine will have a deadline in Dec?
