### ISSUE TITLE
Enable sponsor logos on SCALE 14x site

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#129]
Hey @rgolan, We should have a few sponsors and exhibitors in the website at this point. Can we enable the sponsor logo side bar?

Thanks,
Ilan

**Comment by rgolan** [comment]
I've enabled the block but only two logos show up. Is that what you expected?

**Comment by irabinovitch** [comment]
Thanks.  I've published  a few more sponsors to fill it out.
