### ISSUE TITLE
Linux Pro Magazine - Banner Ads

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#130]
We've procured banner ads on the various Linux New Media Sites.

They can accept any of the following sizes:
728x90, 300x250, 160x600

Do we have any of these already?

**Comment by irabinovitch** [comment]
@ScislaC do we have any buttons we can send along?

**Comment by irabinovitch** [comment]
Looks like these match the specs for #141 which are due this week.

**Comment by ScislaC** [comment]
Here are a couple at 300x250, I will target other sizes next...
![scale-14x-banner300x250-blue](https://cloud.githubusercontent.com/assets/1201009/11230236/0d34a2be-8d52-11e5-8f7a-9c81af16623a.png)
![scale-14x-banner300x250-gr](https://cloud.githubusercontent.com/assets/1201009/11230237/0d365f28-8d52-11e5-9866-d1d4624c419a.png)

**Comment by irabinovitch** [comment]
sent these in to LWN

**Comment by ScislaC** [comment]
Matching 728x90, will do the last one next.
![text7265-8](https://cloud.githubusercontent.com/assets/1201009/11287155/6d331d80-8ece-11e5-8940-fc5bbfc59345.png)
![text7265-7](https://cloud.githubusercontent.com/assets/1201009/11287167/80507214-8ece-11e5-957a-369c813ed259.png)

**Comment by ScislaC** [comment]
Here's a blue one for the 160x600 in blue (one w/ Troy, one w/o in case there's a preference)
![scale-14x-banner160x600-blue](https://cloud.githubusercontent.com/assets/1201009/11288316/eb4fb9c2-8ed7-11e5-8950-898d5fd4b44b.png)
![scale-14x-banner160x600-blue2](https://cloud.githubusercontent.com/assets/1201009/11288319/eed53478-8ed7-11e5-9dbc-8d16d065b52d.png)

**Comment by irabinovitch** [comment]
Awesome! I think this has us covered.  FWIW I always like including Troy.
