### ISSUE TITLE
Update dates on exhibitors page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#132]
hey @rgolan  can we update the days listed on the exhibitors page for Jan 2016? 

https://www.socallinuxexpo.org/scale/14x/exhibitors

Jan 22, 23, 24

rather than the feb dates

**Comment by rgolan** [comment]
The dates have been updated but the times are the same as last year.

**Comment by irabinovitch** [comment]
Thanks
