### ISSUE TITLE
add security as an option to CFP

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#134]
Hey @rgolan , Can we add security as a track option in the call for papers?

**Comment by rgolan** [comment]
Do you mean add a Security term to the Topic dropdown or edit the CFP suggested Topic of Interest or both?

**Comment by irabinovitch** [comment]
In the dropdown.  It's already listed on the [CFP](https://www.socallinuxexpo.org/cfp/) page just not in the drop down.

**Comment by rgolan** [comment]
I've added Security to the options for Topic on Presentations.

**Comment by irabinovitch** [comment]
Thanks!
