### ISSUE TITLE
ads for lwn.net

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#141]
We've arranged to run banner ads on lwn.net.  They require them in 728x90 and 300x250.
Our point of contact is going on vacation for the next several months after this week, so best to get them in before Friday.

We should be able to reuse these for #130 as well.

**Comment by ScislaC** [comment]
Here are a couple at 300x250, I will target other sizes next...
![scale-14x-banner300x250-blue](https://cloud.githubusercontent.com/assets/1201009/11230236/0d34a2be-8d52-11e5-8f7a-9c81af16623a.png)
![scale-14x-banner300x250-gr](https://cloud.githubusercontent.com/assets/1201009/11230237/0d365f28-8d52-11e5-9866-d1d4624c419a.png)

**Comment by irabinovitch** [comment]
sent these in to LWN. Will send the others when they are available.

**Comment by ScislaC** [comment]
Here's matching 728x90 ads.
![text7265-8](https://cloud.githubusercontent.com/assets/1201009/11287155/6d331d80-8ece-11e5-8940-fc5bbfc59345.png)
![text7265-7](https://cloud.githubusercontent.com/assets/1201009/11287167/80507214-8ece-11e5-957a-369c813ed259.png)

**Comment by irabinovitch** [comment]
Thanks. I've sent these along.
