### ISSUE TITLE
Enable Speakers & Presentations Links

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#142]
As we're starting to mark speakers as accepted and publish their talks, we should enable the speakers & presentations links under the Information menu.

**Comment by rgolan** [comment]
I added both a Speakers and Presentations menu item on the 14x site.

**Comment by garethgreenaway** [comment]
Thanks Ron. It looks like presentations from previous years are showing up on the speakers page.

**Comment by rgolan** [comment]
I tried to fix this just now but it's going to take more time and I have to leave. I'll work on it tonight. Do you want me to leave the Speakers menu item enabled or disable it?

**Comment by garethgreenaway** [comment]
Let's disable it until it's fixed.

**Comment by rgolan** [comment]
I've fixed the speaker view and reenabled the menu link.

**Comment by garethgreenaway** [comment]
Thanks Ron!
