### ISSUE TITLE
Proofreading of Session and Speaker Content

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#143]
We've nearly finalized the SCALE schedule and session selections.  The next step we generally take in planning is to proofread bios and abstracts ahead of sending them off to print in the final program.

More detailed instructions will be posted shortly.

**Comment by lcafiero** [comment]
I've gone through all of them and fixed the mistakes I saw, and they were minuscule -- a left-out apostrophe, missed capitalization, etc. There were a lot of formatting issues -- extra lines, etc. -- which I fixed. Obviously if someone else wants to go through and just fix misspellings and grammar (and not rewrite anything, though you may be tempted to), that would be great.

**Comment by irabinovitch** [comment]
@lcafiero Just to confirm did you go through the full list, or the ones presently published on the site? We've still got more going out as speakers ACK their participation.

**Comment by irabinovitch** [comment]
@lcafiero  ?

**Comment by lcafiero** [comment]
Let me know where it is and I'll take care of it.
