### ISSUE TITLE
14x T-Shirt Design - Deadline 1/6

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#145]
We need a design for the SCALE 14x t-shirt design.

**Comment by garethgreenaway** [comment]
@ScislaC Thoughts on this one?  The design eg. number of colors, etc. can effect the price.

**Comment by ScislaC** [comment]
We've been on 1 color for the past couple years, so it was my assumption that we were sticking to that.

**Comment by garethgreenaway** [comment]
No worries, wasn't sure if you wanted to get crazy this year :)

**Comment by garethgreenaway** [comment]
@ScislaC Thoughts on shirt color for this year?

**Comment by ScislaC** [comment]
If we're going with the same style as last year, the Irish Green is available in all types.

**Comment by irabinovitch** [comment]
Did we decide on a style?

**Comment by garethgreenaway** [comment]
@ScislaC Any ideas for a design this year?  Let's go with the irish green color.  Perhaps something using elements of Pasadena?

**Comment by ScislaC** [comment]
I'm working on the design. I'm playing catch up atm as I had some health related delays force me to push things back...

**Comment by garethgreenaway** [comment]
Okay cool.  Let me know if/how I can help at all.

**Comment by garethgreenaway** [comment]
@ScislaC Any updates on the tshirt design?

**Comment by irabinovitch** [comment]
@garethgreenaway Trying to help josh prioritize the order the ever increasing number of design requests need to be done in.  Can you help add a due date to the title of the ticket? We're using the due date to determine the order in which we're tackling them.

**Comment by irabinovitch** [comment]
*bump* re: due date.

**Comment by garethgreenaway** [comment]
I updated the title with a TBD and once I know the date I'll update it, and continue working with Josh on the design. Given the holidays last week, the vendor was closed, I'd imagine I'll hear back from them on Monday.

**Comment by garethgreenaway** [comment]
@ScislaC FYI, updated the deadline for the artwork on the shirts.

**Comment by garethgreenaway** [comment]
Artwork for all 3 designs sent off to the vendor.  Thanks @ScislaC!
