### ISSUE TITLE
Enable sign.xml for SCALE 14x

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#146]
Enable sign.xml for SCALE 14x.  No rush, something for after the holiday.

**Comment by rgolan** [comment]
The sign export is already enabled but it won't show presentations that have both a room and time assigned.

https://www.socallinuxexpo.org/scale/14x/sign.xml

**Comment by garethgreenaway** [comment]
Perfect!  Thanks!
