### ISSUE TITLE
Create Event Page for SCALE TNG

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#147]
Lets create an event page for TNG explaining its goals and showing that specific schedule so we have something to share with schools and teachers.  At the moment it gets lost in the rest of the site content.

**Comment by irabinovitch** [comment]
Thanks for adding the initial text.  Since we know who the speakers are even if we dont know the timing yet, can we list their names in the schedule section?

We should also include instructions for how kids who want to register to attend should do so.

**Comment by irabinovitch** [comment]
@garethgreenaway Thoughts on my feedback above?

**Comment by garethgreenaway** [comment]
I'm actively working on the TNG event page and should have some updates later today.

**Comment by irabinovitch** [comment]
Any luck on this one? With the schedule up it would be great to have a landing page that sells the event to teachers and parents, along with a schedule.  We should also include instructions for how kids who want to register to attend should do so. (eg do kids need to pay? which pass $75, $15?)

Would like to send this to all the schools in the Pasadena area, but theres not much info for them to go on when they get to the page.

**Comment by irabinovitch** [comment]
I know folks are busy with the holidays, but I want to get these out first thing Monday so they have time to coordinate chaperones, travel, etc.  Unless I hear otherwise, I'll work on fixing the content with the feedback above over the weekend.

**Comment by garethgreenaway** [comment]
I'm planning on working on the TNG event page today, have been waiting on some additional information.
