### ISSUE TITLE
Create Event Page for Ubuntu Summit

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#149]

**Comment by irabinovitch** [comment]
The ubucon.org site is finally getting some content on it. Are we ready to link to it yet?

http://ubucon.org/en/events/ubucon-summit-us/

**Comment by irabinovitch** [comment]
Looks like the site is fully up and has reg info now, just need to create the event page on our end. Happy to help if needed.

**Comment by garethgreenaway** [comment]
The UbuCon Summit event page is created and published on the SCALE site.  It has been up and available for a couple days.  It links to the UbuCon Summit page.
