### ISSUE TITLE
Create event page for Apache BigTop

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#150]
Create event page for Apache BigTop

**Comment by irabinovitch** [comment]
@garethgreenaway any news from bigtop? Happy to reach out to Nate or Konstantin if it'd be helpful.

**Comment by garethgreenaway** [comment]
I'm waiting to hear back from Nate on details.

**Comment by irabinovitch** [comment]
Looks like this was created:
https://www.socallinuxexpo.org/scale/14x/apache-bigtop-workshop
