### ISSUE TITLE
Create event page for  HAM Testing

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#153]
Create event page for  HAM Testing

**Comment by irabinovitch** [comment]
@hriday  Can we create a "special event" for HAM testing and maybe a blog post explaining how to get involved?

**Comment by irabinovitch** [comment]
@hriday  are we still waiting on a reply from them?

**Comment by irabinovitch** [comment]
@hriday I think you said we have this info now? Need help creating the page?

**Comment by hriday** [comment]
Yup, it's ready. And yes, I'll need some help with the page. Any pointers?

Here's the info:

Amateur Radio at SCALE

SCALE's getting into amateur in a big way this year, starting with offering
HAM exams. The tests will be conducted on Sunday, from 11 AM to 3 PM, at
our PCC venue. Walk-in's welcome.

We also have a special treat for all the HAM's and wannabe HAM's in
attendence. The Amateur Radio Emergency Service (ARES) of Southern
California will demonstrate their mesh network and how that facilitates
emergency communication.

SCALE will also have it's own channel for the duration of the event, so if
you have a licence and a radio, bring it over. Come be a part of the HAM
community.

For those of you that are intested in taking the exams, here's the link to
the question banks for the three classes:

Technician : http://ncvec.org/downloads/2014-2018%20Tech%20Pool.pdf
General :
http://www.ncvec.org/downloads/FINAL%20Revised%202015-2019%20General%20Class%20Question%20Pool%202-11-2015.pdf
Extra : http://www.ncvec.org/downloads/REVISED%20Extra%20Class%20Pool.doc

You can find a lot more information on the exams and how to get licensed
here : http://www.arrl.org/question-pools

H.

**Comment by irabinovitch** [comment]
Thanks Bala. I posted this for you as a blog post here:
https://www.socallinuxexpo.org/blog/amateur-radio-scale-14x

Once we have the exam and frequency details we can turn it into an event page as well.
