### ISSUE TITLE
Bugs with Multiple Speakers

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#154]
When there are multiple speakers for a presentation, only one speaker headshot show up and the link to the speaker information page is a combination of the two names.  An example, https://www.socallinuxexpo.org/scale/14x/presentations/scale-speaker-training-seminar

**Comment by rgolan** [comment]
Thanks for reporting this, Gareth. It's fixed now.

**Comment by rgolan** [comment]
I guess the link is still not fixed. Working on it now.

**Comment by garethgreenaway** [comment]
@rgolan Thanks!

**Comment by rgolan** [comment]
The speaker name links are fixed now too.

**Comment by garethgreenaway** [comment]
Perfect!  Thanks!
