### ISSUE TITLE
Invalid URL for Exhibitor Pages

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#155]
Attempting to add the following URL to an exhibitor page, I told me that it was invaild:
https://tox.chat/

**Comment by rgolan** [comment]
The link field type had some built in validation. I guess it didn't accept .chat domains or something. I just disabled the validation. Please try again with that URL.

**Comment by garethgreenaway** [comment]
good to go!  Thanks!
