### ISSUE TITLE
Provide Badge Design Requirements

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#156]
Bala, Once you know the specs of the badge design please share here so that @ScislaC  and crew can start working on it.

**Comment by irabinovitch** [comment]
@hriday  reminder that @ScislaC  needs specs to start work on 157

**Comment by irabinovitch** [comment]
@hriday Are we set with Josh on this one?

**Comment by hriday** [comment]
Mostly. Final touches with the printers remaining.

**Comment by irabinovitch** [comment]
OK. Closing then since requirements were provided.
