### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#158]
Hi Ron,

The Contact Us page in the footer links to a SCALE 13x version (https://www.socallinuxexpo.org/scale/13x/contact-us)  

Since we've got new teams and team members can we link to a 14x page? I'd like to add Phil and a few others to it. Thanks.

**Comment by rgolan** [comment]
Do you care if we preserve the 13x Contact Us page or can we just update it and change the link to a 14x one?

**Comment by irabinovitch** [comment]
@rgolan either way.

**Comment by irabinovitch** [comment]
thanks. all set.
