### ISSUE TITLE
display promo items 

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#160]
@rgolan  Any chance we can setup the promo items page to preview like they were back in https://www.socallinuxexpo.org/scale10x/promo-items ?

**Comment by rgolan** [comment]
I added a link to the main menu. If we need to display all the images on that page, I'll need to rework the view.

**Comment by irabinovitch** [comment]
Thanks Ron.  I mostly interested in the view, assuming its not too much work.  I think giving people a preview will encourage them to use it more.

**Comment by rgolan** [comment]
I reworked the promo items page to show the images. Note that the banners are blocked by ad blocking software so you don't anything there now. I remember now that was the problem before. Let me know what you think we should do.

**Comment by irabinovitch** [comment]
I vaguely recall we fixed it in the past by just renaming the files.
