### ISSUE TITLE
Issue with presentation links

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#162]
08:54   kaledann: Gareth: New problem.  If you access the presentation directly, and then click on Audience:Everyone and Topic:Youth, it links to something like https://www.socallinuxexpo.org/taxonomy/term/4                                                                      
08:54   kaledann: https://www.socallinuxexpo.org/scale/14x/presentations/open-source-radio is where I saw it

**Comment by rgolan** [comment]
This should be fixed now.

**Comment by garethgreenaway** [comment]
Awesome.  Thanks!
