### ISSUE TITLE
Link to BoF signup page

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#163]
Will defer to Ron on the best place to put this, Hans and Jill put together a Google Form for the signup for BoFs.  Where can we link to it from the site?

**Comment by irabinovitch** [comment]
I've built the page in the past and will set it up again.

**Comment by irabinovitch** [comment]
Created last week.  Embedded the form as an iframe on the event page and on the blog post again. We'll ask PR folks to schedule some tweets.

**Comment by irabinovitch** [comment]
Created last week.  Embedded the form as an iframe on the event page and on the blog post again. We'll ask PR folks to schedule some tweets.
