### ISSUE TITLE
Additional banner ads

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#165]
- [x] 612px × 202px

**Comment by irabinovitch** [comment]
@ScislaC  i think you said this one was ready/in progress?

**Comment by ScislaC** [comment]
Yeah, I have one I'm not thrilled with (layout-wise), but it's something.

![612x202](https://cloud.githubusercontent.com/assets/1201009/11858028/831eefd0-a412-11e5-9b1f-a709878a8bbc.png)
