### ISSUE TITLE
Color for Security Track

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#166]
The security track in the schedule needs a color.

**Comment by rgolan** [comment]
I added a color for Security and while I was at it, I added one for Legal & Licensing too. Any idea why DevOps and General are showing up on the legend on Friday's schedule? I think something might be assigned to that day but outside of the times shown on the schedule.

**Comment by garethgreenaway** [comment]
I found a few like that.  I can check the sign.xml and see which sessions are wrong.

**Comment by rgolan** [comment]
Great idea!

**Comment by garethgreenaway** [comment]
Can't find any Devops talks that are scheduled on the 22nd.

**Comment by irabinovitch** [comment]
None of the devopsday talks are published yet, but they will all occur on Friday

**Comment by rgolan** [comment]
I found this.
https://www.socallinuxexpo.org/node/1392/edit
This is what's causing General to show up, I think. It started in 2015 and ends in 2016. Still looking for the DevOps lurker.

**Comment by rgolan** [comment]
I changed the schedule legend to only show tracks for which there is at least one published presentation. That got rid of the DevOps in the legend. Should that presentation by Deb Nicholson have been just on that day on 2/22/2015 ?

**Comment by irabinovitch** [comment]
Fixed Deb's session from last year.  Are we still having an issue with DevOps sessions?

**Comment by rgolan** [comment]
I fixed the DevOps thing.

**Comment by irabinovitch** [comment]
Cool. Closing. Thanks!
