### ISSUE TITLE
Video Stream Artwork - Due 1/18

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#168]
@socallinuxexpo/scale-av has asked that we provide a background image for the video streams for this year.  Here are two examples from past streams.  The black areas will be replaced by speaker and projector video. If someone feels enterprising enough we could probably even make the background a video loop.
​​​​
SCALE 13x
https://drive.google.com/file/d/0BzUa2lspCgF2cTItQlZNRkJpZndmTE5QcHgwdVA5QnJvbmtj/view?usp=sharing

Hackaday
https://drive.google.com/file/d/0BzUa2lspCgF2Y1JnOUpEdGxmY1k4dE0xelE5c29JNlhfNzdr/view?usp=sharing

**Comment by ScislaC** [comment]
Here's one for this year. It is sized for 4k (I highly doubt we're using it at any level, but it's easier to scale down)... ![video1](https://cloud.githubusercontent.com/assets/1201009/12477092/62edd9ce-bfe2-11e5-82d4-9346dfa94adc.png)
