### ISSUE TITLE
Speaker link wrong

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#171]
https://www.socallinuxexpo.org/scale/14x/presentations/nomad-introduction-cluster-schedulers

speaker page links to:
https://www.socallinuxexpo.org/scale/14x/speakers/patrick-o%27connor

but should be:
https://www.socallinuxexpo.org/scale/14x/speakers/patrick-oconnor

**Comment by rgolan** [comment]
The apostrophe is breaking it. I'll look at this weekend.

**Comment by rgolan** [comment]
This is fixed now. I had to some string manipulation in a views template.

**Comment by garethgreenaway** [comment]
Awesome!  Thanks Ron!
