### ISSUE TITLE
Re-enable Keynote topic

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#172]
We have two keynotes in the system, can we re-enable the keynote topic to associate with those two talks.

**Comment by rgolan** [comment]
I think the way we did this last year is we shut down the CFP so any speaker can't change their presentation to a Keynote. Or possibly, we just made the topic inaccessible to the speaker role. Would that latter option work or do we still have speakers creating presentations?

**Comment by garethgreenaway** [comment]
Would be better, if we can, to disable it for the speaker role.  We always seem to need to have the CFP system left open into SCALE.

**Comment by rgolan** [comment]
I'm not sure if I was clear. The topic field will be inaccessible to Speakers,  not just the Keynote topic. Is that ok?

**Comment by rgolan** [comment]
I just thought of way to just exclude the Keynote topic from speakers. I could make some other roles able to assign it. Trying it now.

**Comment by garethgreenaway** [comment]
i'm not seeing it as an option on this talk:
https://www.socallinuxexpo.org/node/2584/edit

**Comment by rgolan** [comment]
I'm still working on it. It'll be there soon.

**Comment by rgolan** [comment]
Do you see it now?

**Comment by garethgreenaway** [comment]
Ah sorry. I misread your comment as "Try it now."  Let me take a look.

**Comment by garethgreenaway** [comment]
Now I see it.

**Comment by garethgreenaway** [comment]
All set!  Thanks!
