### ISSUE TITLE
Expand cells in schedule slightly

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#173]
Can we expand the cells in the schedule slightly?  For some of the shorter sessions, eg. 15 minutes the title is cut off.  Dropping it down a bit would help a lot.

**Comment by rgolan** [comment]
I don't know what to do with those. If I expand 15 minute sections to accommodate that then 1 hour sections will too much empty space. I'm wondering if we should have a 'hide from schedule pages' checkbox in the presentation so it will show up in the presentation pages but not the schedule and then the schedule could have a large event with a link to another page with detailed schedule. I think we had the separate pages like that in past years.

What do you think?

**Comment by garethgreenaway** [comment]
We could try that.  One question I have, how will those show up in the XML and consequentially on the signs?

**Comment by garethgreenaway** [comment]
Found a workaround.
