### ISSUE TITLE
Bag Art for 14x

### ISSUE THREAD

**Issue by ScislaC** [socallinuxexpo/SCALE-Design#174]
I had been in communication with Bala off-track about this. Here is the proposed design.

![bag2c](https://cloud.githubusercontent.com/assets/1201009/11857736/e31f7574-a40f-11e5-8303-9481cfc30d68.png)

**Comment by irabinovitch** [comment]
Cool. What color would the bag and print be?

**Comment by garethgreenaway** [comment]
@ScislaC This looks awesome!  A black bag with white ink would look awesome with this design.

**Comment by ScislaC** [comment]
I'm pretty open to colors. My thought would be either green w/ yellow ink or Gareth's black bag w/ white is cool by me too... so, here's the simulated colors.

![bag2c-](https://cloud.githubusercontent.com/assets/1201009/11858570/ad57194e-a417-11e5-9789-9ef279ad1c35.png)
![bag2c--](https://cloud.githubusercontent.com/assets/1201009/11858659/4327b2f8-a418-11e5-81c1-270519e31508.png)
![bag2c---](https://cloud.githubusercontent.com/assets/1201009/11858663/47164866-a418-11e5-977c-d30672e60559.png)

**Comment by ScislaC** [comment]
Ahhh... moot discussion, apparently the bag provider only has one color in January.

**Comment by irabinovitch** [comment]
Hot pink right?

**Comment by hriday** [comment]
Dirty blonde.

Actually navy blue

**Comment by garethgreenaway** [comment]
The ones from last year were navy right?  Navy + White would look sharp.

**Comment by irabinovitch** [comment]
@hriday do we have a due date for this one? just trying to help get all our requests prioritized.

**Comment by hriday** [comment]
Bags have been ordered. And paid for. All I need is the shipping address.

**Comment by irabinovitch** [comment]
Ah perfect. Closing. Wil lsend you shipping info shortly.
