### ISSUE TITLE
remove unused rooms from schedule

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#175]
Saturday and Sunday
===
Ballroom GH
Room 207
Room 208

**Comment by rgolan** [comment]
I've disabled those rooms from appearing in Saturday's or Sunday's schedule.

**Comment by irabinovitch** [comment]
Thursday
=========
Ballroom G
Ballroom H
Ballroom GH
Ballroom IJ
Ballroom I
Ballroom J
Room 104
Room 105
Room 104/105
Room 211
Room 209
Room 210
Room 209/210

208 Break Room
205 NOC
215 NOC

Friday
========
Ballroom A
Ballroom B
Ballroom F
Room 103
Room 209
Room 210
Room 209/210

Sunday
=========
Room 212/214

**Comment by rgolan** [comment]
I've disabled the listed room on those days but many of those rooms were not even in the website schedule at all. Please check the production site to confirm that the proper rooms are now being displayed.

**Comment by irabinovitch** [comment]
Thanks Ron. Looks good so far. will ask others to take a look as well.

I'm  trying to think if what we should Ballroom DE. It just has the keynotes in the morning, and empty rest of the day.

**Comment by garethgreenaway** [comment]
@rgolan While we're hiding the unused rooms, can we add in the Exhibit Hall, so we add the hours for that to the schedule.

**Comment by rgolan** [comment]
Is the 'Exhibit Hall' a separate room that can be labeled 'Exhibit Hall' in our system or is it a space that is also used for other events that are already in the schedule?

**Comment by irabinovitch** [comment]
Theres a room at the venue called Exhibit Hall A and Exhibit Hall B.  I would just list them as "Exhibit Hall"

**Comment by rgolan** [comment]
Which days should Exhibit Hall appear in the schedules?

—
Ron Golan
rgolan@superconcentrated.com

**Comment by garethgreenaway** [comment]
Friday, Saturday and Sunday

**Comment by rgolan** [comment]
I’ve added Exhibit Hall as a room option and added it to the schedules for Friday, Saturday and Sunday. It’s way off on the right. If you want it moved to the far left, let me know.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by garethgreenaway** [comment]
Excellent.  I've added the exhibit hours to the schedule.  Thanks!
