### ISSUE TITLE
Artwork for Entrance Units - Due 1/8

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#176]
Size specifications for artwork:
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/entrance_units/ENTRANCE-UNIT.pdf

Guidelines:
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/entrance_units/60GraphicsDigitalFilePreparation.pdf

Uncharted waters since we've never done this before but let me know if you have questions. :)

**Comment by irabinovitch** [comment]
Where will these be located?  We likely need to include sponsor artwork on these  depending on location.  Do we have a cost on these? or are they included in the existing agreement?

**Comment by garethgreenaway** [comment]
They will likely be located at the entrance to the exhibit hall.  The price is not include in the agreement, but I believe it was called out in the proposal.  I can send the information along if you need it.

The two side panels (PA.3) would be a good location for any sponsorship logos.

**Comment by irabinovitch** [comment]
@garethgreenaway Do we have the deadline on when these would be needed?

**Comment by garethgreenaway** [comment]
@ScislaC FYI, Blaine would need the artwork for the entrance panels by Friday January 8th

**Comment by irabinovitch** [comment]
@garethgreenaway same 1/8 due date as #177 ?

**Comment by ScislaC** [comment]
Just following up from earlier discussion.
@irabinovitch Did these need (or do we want) to have sponsor artwork on them?
@garethgreenaway How many of these will there be?

**Comment by garethgreenaway** [comment]
@ScislaC I believe we would only have one of these.

**Comment by irabinovitch** [comment]
@ScislaC Yes, we need to include the HP logo on these.

**Comment by garethgreenaway** [comment]
Artwork sent off to vendor.

**Comment by irabinovitch** [comment]
Where was it sent?  HP should have been given a chance to approve since it needs to have their artwork on it.

**Comment by garethgreenaway** [comment]
It was sent to Blaine, you can send them this:
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/entrance_units/EntUnit.pdf

**Comment by irabinovitch** [comment]
Thats not the right logo. These needs to be canceled immediately.

**Comment by ScislaC** [comment]
@irabinovitch Where are the current logos? A few years ago they had used a more 3d looking logo and but somewhere in the last couple years they did the flattened rebranding (such as if you go to hp.com).

**Comment by irabinovitch** [comment]
Dropbox should have a zip file containing the current current set of logos.

**Comment by ScislaC** [comment]
@irabinovitch I don't know that I have received an invite or link for a dropbox folder containing these types of resources (I've received links for specific items).

**Comment by ScislaC** [comment]
@irabinovitch OK, got it. The issue was it was Hewlett Packard Enterprise, not HP... that's why I was confused. Will get it corrected.

**Comment by ScislaC** [comment]
@irabinovitch We also have a Registration Display as well which will be produced sometime tomorrow. Does they need to be represented there as well? Regarding this display, did you want any additional text by their logo such as "Sponsored by" or "With generous support from" or something of that nature?

**Comment by irabinovitch** [comment]
"Sponsored by" works.

**Comment by ScislaC** [comment]
@irabinovitch Feedback welcome. If it looks okay by you, please run by HPE. https://www.dropbox.com/s/7fouvj0uhpf1sni/PA3-right-hpe.pdf?dl=0

**Comment by garethgreenaway** [comment]
What are we having HPE approve?  Can we have Blaine begin printing the other pieces while we're waiting for HPE to approve the logo on PA3-right?  Or does their sponsorship agreement include approval over the entire entrance unit design?

**Comment by garethgreenaway** [comment]
@irabinovitch Did we hear back anything from HP?  Blaine is waiting to go to print, if they can begin printing the other panels while we wait that would be great.

**Comment by irabinovitch** [comment]
I sent it to them at 10pm pst last night. I'll give them until noon today
and call them.

**Comment by garethgreenaway** [comment]
To confirm, we're waiting on all printing before HPE approves the design.

**Comment by garethgreenaway** [comment]
@irabinovitch After noon, any updates?

**Comment by irabinovitch** [comment]
All set. Just spoke with them. Thanks

**Comment by garethgreenaway** [comment]
Thanks.  New graphics uploaded to Blaine and they'll begin printing.
