### ISSUE TITLE
Artwork for Aisle Signs - Deadline 1/8

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#177]
Signs in exhibit hall hanging from the ceiling indicating the aisle blocks, eg. 700 block.  Will have more information on this tomorrow.

**Comment by irabinovitch** [comment]
@garethgreenaway  Did we get the specs for this on Tuesday?

**Comment by irabinovitch** [comment]
@garethgreenaway ping?

**Comment by garethgreenaway** [comment]
@ScislaC Here is the information for the aisle signs:
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/aisle_signs/BCS_Stock_Aisle_Banner.pdf

And some examples:
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/aisle_signs/Stock_aisle_sign.jpg
https://dl.dropboxusercontent.com/u/40455/SCALE/14x/aisle_signs/WPSS%20%20copy.jpg

For the one without logo no work necessary on your part.

Deadline would be January 8th.

Installation is $250/each to install & dismantle.  Custom aisle signs are $270/each + $250 for install/dismantle.

**Comment by ScislaC** [comment]
@garethgreenaway Okay, so they have their stock aisle signs and I would need to produce the artwork for ones akin to the WPSS ones? If so, that appears to be wider than their stock aisle signs, so I would just need to know the width then (I'm assuming the height would be the same as listed in that PDF).

**Comment by garethgreenaway** [comment]
@ScislaC Let me find out the size for that one.  Might not hear back from them until next week.

**Comment by garethgreenaway** [comment]
@ScislaC Contact at Blaine need to confirm but he believes it's 4' x 8', we'll know for certain on Monday.

**Comment by ScislaC** [comment]
@garethgreenaway I just wanted to follow up and ask if they have provided specs yet.

**Comment by garethgreenaway** [comment]
Let me follow up with them on that.

**Comment by garethgreenaway** [comment]
The dimensions for the custom bit would be 48" x 96"h

**Comment by ScislaC** [comment]
Okay, one last Q... is this one single design or are there multiple design opportunities? If multiple, how many (I have a fun idea, but would need numbers to do it right)?

**Comment by garethgreenaway** [comment]
We can have multiples but we pay $270 per design.

**Comment by ScislaC** [comment]
I'm kind of lost... Is it 270 per banner (minus the install/removal fees)
or 270 per distinct design (potentially plus more for physical production
and the separate related labor fees)?

How many banners are we currently assuming either way?

Cheers,
Josh

**Comment by irabinovitch** [comment]
According to the contract:
They will print One sign per aisle free if we dont customize.  But will charge $250 to hang it.
If we customize the artwork it's an additional $275 per sign, not per design.

I'm thinking we might want to skip this entirely.  If I'm reading this all right it'd be

Custom Artwork:  (250+275)*7 =$3,675
No Design  250*7 = $1750.

I dont think this is a good use of our funds.

**Comment by irabinovitch** [comment]
If we feel need this type of direction we can probably get the floor stickers from sticker mule at *much* cheaper.

**Comment by garethgreenaway** [comment]
It is $250 / sign to hang, so without a custom design it would be $1750.  I can check with Blaine and clear up the confusion for the custom signs, if we want to move forward on them.  If not, we can scrap it and go with something from Sticker Mule instead.

**Comment by ScislaC** [comment]
I'm not suggesting it, but we could likely get a number of other more diversified things produced for that amount of money. Speaking of which, are we doing any banners or anything for any walls?

**Comment by garethgreenaway** [comment]
Let's skip them then.
