### ISSUE TITLE
Floor Graphics - Due 1/10

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#178]
Via a recent sale at Sticker Mule and their sponsorship we have an opportunity for (10)  24"x"24 or 36"x36"  floor graphics to place around the venue.   These are removable and weather resistant.

They could be used for directional signs, general SCALE branding of the building, or anything else we have in mind.

If we want to order this, the due date is: 1/10.

https://www.stickermule.com/products/floor-graphics/

**Comment by ScislaC** [comment]
@irabinovitch @garethgreenaway Any thoughts on what we want to do with these? Can they go on the aisle carpets in the Expo Hall? Do we want them by entry doors welcoming people?

**Comment by irabinovitch** [comment]
@ScislaC My thought was to spread them around the venue, halls and entrances. Or on the side walk between the two buildings

**Comment by ScislaC** [comment]
So is 10 how many we ended up with?

**Comment by irabinovitch** [comment]
@ScislaC We have 10 at the moment. We can probably cut back or add a few more.

**Comment by garethgreenaway** [comment]
If we're using as directional signs, the hallways outside the exhibit hall and the ballrooms would be good.  The areas in the lower level in the conference center side also.  Maybe a couple generic ones with the SCALE logo on it in various places.  A couple as directional signs in registration too.
