### ISSUE TITLE
Outdoor Banners at Convention Center - Due Date TBD

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#179]
During the last onsite tour @ScislaC  had asked about getting the lampost banners SCALE branded. PCC has confirmed we can brand the buildings and lamp posts if we'd like.  Links to specs below.

Lets chat about what makes sense given we're already doing #178 and #176 .  The hanging cost is $100 per banner, in addition to whatever the banner printing itself would cost.    Ideally we'd look for non year specific artwork on some of these so they can be reused in the future.   

[Banner Specifications_Pasadena Convention Center.pdf](https://github.com/socallinuxexpo/SCALE-Design/files/75141/Banner.Specifications_Pasadena.Convention.Center.pdf)

From this pdf the following ones are available to us should we choose to do them:
* Conference Center 
* Exhibit Hall and Ballrooms
* Lamp Posts

As we aren't in the civic auditorium we cannot brand that building.

**Comment by ScislaC** [comment]
For example on the Conference Center we could do the 26' with "Southern California Linux Expo" and with the vertical flanking banner(s) being year specific. We could do Troy on the Left flank, and the stacked SCALE 14x 2016 on the Right flank for example. Lamp posts seem like the type of thing that tend to be year specific. Thoughts?

**Comment by garethgreenaway** [comment]
+1

**Comment by irabinovitch** [comment]
Hi Josh, We have a 2 non year specific large banners although I think they are either 6' or 9' rather than 26' sot hey probably dont fit here  We've had those for a few years though, so its probably reasonable to replace them with larger units, or move them indoors.  

Anyways, yes, I had similar thoughts about a SCALE banner horizontal and Troy on one or both sides. Although I'm trying to use SCALE more and more and focus on the spelled out name less since we have so much more non-linux content these days.

Are you thinking the same design for the banners on both sides?

Open to ideas on the lamp posts.  Maybe alternate between year specific and Troy?

**Comment by ScislaC** [comment]
Good to know about the focus on branding. I try to not abuse the fully spelled out one, but in cases like and on the Entrance Unit where it's a rather long horizontal space that isn't very tall vertically it makes for a good filler of space.

As for the vertical flank banners on, I could totally go either way. I'm a fan of symmetry, so I definitely wouldn't oppose the same design on both sides.

**Comment by irabinovitch** [comment]
Looks like we aren't going to be able to use the lamp posts.  Someone else has something up.  Trying to get details on that...

**Comment by irabinovitch** [comment]
I've got quotes from a few local vendors, and a few out of town vendors. Out of town is significantly cheeper, but requires artwork today or tomorrow at the latest due to shipping either cross country or internationally.

**Comment by irabinovitch** [comment]
ordered
