### ISSUE TITLE
List of Room Sponsors - Deadline 1/18

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#180]
Need the list of what groups are sponsoring what rooms to update the in room sign software.

**Comment by garethgreenaway** [comment]
Thoughts on this?

**Comment by irabinovitch** [comment]
As in past years, it wont be ready until the week before the event at the earliest.  Too many last minute sponsors for this option.

**Comment by garethgreenaway** [comment]
Yup.  That's why the deadline is the 18th of January.  Are there any sponsors so far?  Even if they're not official, it's not something that will be publicly visible until everything is setup at the PCC anyways.
