### ISSUE TITLE
Talk Time and Room Missing for Anonymous

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#181]
Talk Time and Room Missing for presentation pages for Anonymous users.

**Comment by rgolan** [comment]
Could you point to a specific page?

**Comment by garethgreenaway** [comment]
I believe it's any of them:
https://www.socallinuxexpo.org/scale/14x/presentations/keynote-2
https://www.socallinuxexpo.org/scale/14x/presentations/broken-linux-performance-tools

Only if you're logged out.

**Comment by rgolan** [comment]
I see. I guess we had it off while the schedule was being created and didn't turn it back on. I'm looking into it now.

**Comment by garethgreenaway** [comment]
Thanks!

**Comment by rgolan** [comment]
That's fixed now.

**Comment by garethgreenaway** [comment]
Thanks Ron!
