### ISSUE TITLE
Evening Entertainment Topic

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#182]
Enable Evening Entertainment topic for presentations so we can flag events like Weakest Geek & Game Night.

**Comment by irabinovitch** [comment]
That option exists for notices, which are a better fit for these since they aren't tied to individuals.

**Comment by garethgreenaway** [comment]
The notices did not appear on the digital signs, which is the reason I'm asking to include the Evening Entertaining topic, which we had last year.  Again, I would ask that you please stop closing my tickets.

**Comment by irabinovitch** [comment]
Please fix the signs to use notices then.  Please do not use presentations for content without an associated speaker.

**Comment by garethgreenaway** [comment]
The notices do not show up in the XML that is generated by the website, so we use presentations for events that we want to show up on the digital signs.  This is the way this has worked for several years, without issue.  If we change things now to include noticed it's a lot more work for Ron to change and a lot more work for me to filter out breaks & lunches, and other items that should not be on the signs at all.
