### ISSUE TITLE
Add SpeakerTraining Topic

### ISSUE THREAD

**Issue by garethgreenaway** [socallinuxexpo/SCALE-Design#184]
Add SpeakerTraining Topic

**Comment by irabinovitch** [comment]
We shouldn't create new tracks for single sessions. This is a half day tutorial which means it fits into SCALEU and is labeled as such on the website right now.

**Comment by garethgreenaway** [comment]
It's not a SCALEU track and has not been advertised as such.  Please don't close my tickets.

**Comment by irabinovitch** [comment]
SCALE U is anything thats a 1/2 day tutorial. 

@rgolan  please skip this.

**Comment by irabinovitch** [comment]
Re-adding my comment which was deleted.  Any session which is a 1/2 day tutorial falls within the SCALE training program that was SCALE U.  @rgolan  please hold off on this ticket.
