### ISSUE TITLE
Updating the link to the CoC

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/SCALE-Design#186]
Hey Ron,

The Code of Conduct is super buried on the site. A few people reached out this year to ask if we can make it easy to find. Would it be possible to have a link to it on the footer of the site along with "Contact Us" and "About SCALE" and such?

**Comment by rgolan** [comment]
Hi Phil,

I added a link in the footer menu. Please see if that going to the page you want.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by jaymzh** [comment]
Perfect, thanks Ron!
