### ISSUE TITLE
promo items page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Design#26]
Hi Ron,

Can we add the promo-it content type and page again?
We have some small banners Josh made for us in #12  and likely some flyers coming soon.
Would be great to post them.

Thanks!
Ilan

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289198/c7b4c1da-4367-11e5-9854-3f8e2bd9fc49.jpg)
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
